### ISSUE TITLE
Submitting a program repair tool: QACrashFix

### ISSUE THREAD

**Issue by xiongyingfei** [automated-program-repair/automated-program-repair.github.io#6]
{
	    "name": "QACrashFix",
	    "description": "Fixing Java crash bugs by querying StackOverflow",
	    "url": "http://sei.pku.edu.cn/~gaoqing11/qacrashfix/",
	    "target": "Java source code",
	    "title": "Fixing Recurring Crash Bugs via Analyzing Q&A Sites",
	    "authors": "	Qing Gao, Hansheng Zhang, Jie Wang, Yingfei Xiong, Lu Zhang, Hong Mei",
	    "venue": "ASE'15: 30th IEEE/ACM International Conference on Automated Software Engineering",
	    "year": "2015"
	}

**Comment by mechtaev** [comment]
Thanks! Added.
